<<<<<<< HEAD
# Generated by Django 3.2.15 on 2022-09-13 18:51
=======
# Generated by Django 3.2.15 on 2022-09-13 13:25
>>>>>>> 0ac8604088d6005171f4615d8222636f4885af6c

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
=======
                ('book_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('author', models.CharField(max_length=50, verbose_name='author')),
                ('category', models.CharField(max_length=50, verbose_name='author')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='price')),
>>>>>>> 0ac8604088d6005171f4615d8222636f4885af6c
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=50)),
                ('last', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=15)),
=======
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=50, verbose_name='firstname')),
                ('last', models.CharField(max_length=50, verbose_name='lastname')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('password', models.CharField(max_length=15, verbose_name='password')),
>>>>>>> 0ac8604088d6005171f4615d8222636f4885af6c
            ],
        ),
    ]
